controller:
  image:
    repository: jenkins/jenkins
    tag: "2.462.3-jdk17"
    pullPolicy: IfNotPresent

  admin:
    username: admin
    password: admin123

  serviceType: LoadBalancer

  persistence:
    enabled: true
    storageClassName: gp2-csi
    size: 10Gi

  installPlugins:
    - kubernetes:3983.vd7b_82db_e347b_
    - workflow-aggregator:latest
    - git:latest
    - configuration-as-code:latest
    - credentials-binding:latest
    - github:latest

  JCasC:
    configScripts:
      kaniko-pod: |
        jenkins:
          clouds:
            - kubernetes:
                name: "kubernetes"
                namespace: "jenkins"
                templates:
                  - name: "kaniko"
                    namespace: "jenkins"
                    serviceAccount: "default"
                    nodeUsageMode: NORMAL
                    label: "kaniko"
                    containers:
                      - name: "kaniko"
                        image: "gcr.io/kaniko-project/executor:v1.23.2"
                        command: "/busybox/cat"
                        ttyEnabled: true
                        args: ""
                        envVars:
                          - key: AWS_REGION
                            value: "us-east-1"
                    volumes:
                      - emptyDirVolume:
                          memory: false
                          mountPath: "/workspace"

  podSecurityContext:
    fsGroup: 1000
    runAsUser: 1000
    runAsGroup: 1000





