image:
  repository: 306208069784.dkr.ecr.us-east-1.amazonaws.com/lesson-5-ecr
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80
  targetPort: 8000

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70

config:
  DJANGO_SETTINGS_MODULE: myproject.settings
  DEBUG: "False"
  ALLOWED_HOSTS: "*"
  DATABASE_URL: postgresql://user:password@db:5432/mydb
