apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "django-app.fullname" . }}-config
data:
  DJANGO_SETTINGS_MODULE: {{ .Values.config.DJANGO_SETTINGS_MODULE }}
  DEBUG: {{ .Values.config.DEBUG | quote }}
  ALLOWED_HOSTS: {{ .Values.config.ALLOWED_HOSTS | quote }}
  DATABASE_URL: {{ .Values.config.DATABASE_URL | quote }}
